### PR TITLE
allow all rails 8.* versions

### PR DESCRIPTION
**Pull request by doits**

### CODE REVIEW

**Comment by rossta** [comment]
Good catch, thank you @doits

**Comment by excid3** [comment]
@rossta can we get a new release on Rubygems for this? `bundle add montrose` on Rails 8 installs `0.4.0` which was confusing. 🙃

**Comment by rossta** [comment]
@excid3 Done, you should be good to go now!

**Comment by excid3** [comment]
Thanks @rossta!

**Pull request merged**
