### PR TITLE
Rails 8.0 support

### PR DESCRIPTION
**Pull request by TasnimSyncX**
I wanted to use rails 8.0 with this gem and I think many others could benefit as well, so I have attempted to add support based off [support rails 7.1 PR](https://github.com/rossta/montrose/pull/162)

### CODE REVIEW

**Comment by rossta** [comment]
Thanks!

**Comment by TasnimSyncX** [comment]
that was quick, thanks!

**Comment by doits** [comment]
I guess you need `activesupport (>= 5.2, < 9)`, because `<= 8` currently prevents `8.0.0.1` to install.

**Comment by doits** [comment]
... opened #179 for this

**Pull request merged**
