### PR TITLE
Add support for ActiveSupport 5.0

### PR DESCRIPTION
**Pull request by phlipper**
This adds official support for ActiveSupport 5.0. 

To facilitate testing and supporting multiple ActiveSupport versions simultaneously, [`thoughtbot/appraisal`](https://github.com/thoughtbot/appraisal) has been added to the development dependencies. This allows use of Bundler to manage and test multiple dependency versions concurrently in a controlled manner.

**Note:** In the process of adding support for `appraisal`, I found that ActiveSupport version _4.0.x_ fails the test suite. I'm not sure whether the intent is to continue to formally support that version, or drop support in favor of _>= 4.1_, but it is something to be aware of. I have added _4.0_ as an allowed CI failure for now. 

The CI configuration has also been updated to support using `appraisal`, as well as a few other updates to support faster build times.

### CODE REVIEW

**Comment by phlipper** [comment]
I'm not sure what Coveralls is unhappy about, but I'm happy to update this PR as needed.

**Comment by rossta** [comment]
Thanks for the PR, @phlipper. I'll have a chance to take closer look in a few days.

**Comment by rossta** [comment]
@phlipper Thanks for your patience. I've taken a stab at loosening the Simplecov settings for Coveralls in master. Could you rebase? Also, I'd vote for removing the 4.0 gemfile for now. If someone needs to support 4.0, we could consider the required changes and tradeoffs at that time.

**Comment by phlipper** [comment]
@rossta I have rebased on top of the latest master and dropped support for ActiveSupport 4.0 per your request. Thanks!

**Comment by rossta** [comment]
Great!

One more thing: I noticed thoughtbot's README recommends [omitting the `*.gemfile.lock` files from version control](https://github.com/thoughtbot/appraisal#version-control). What do you think?

**Comment by phlipper** [comment]
@rossta `*.lock` files have been omitted.

**Comment by rossta** [comment]
Thanks for the PR, @phlipper!

💜💜💜

**Comment by phlipper** [comment]
@rossta would you please release a gem update with these changes when you get a moment? Thank you for the gem and the consideration!

**Pull request merged**
