### PR TITLE
Add Except for options & chainable

### LINKED ISSUE #19: Implement :except option

### PR DESCRIPTION
**Pull request by thewatts**
This adds an `Except` rule, as well as the ability to have `:except` as
an option, and the ability to chain `.except` into the recurrence.

Also, removes todo for Except syntax in README.

---

This fixes #19

### CODE REVIEW

**Comment by rossta** [comment]
@thewatts Thanks for the PR! It would be interesting to consider what it might mean to handle exception values in other time increments, like hour, month, year, etc. This looks like a good start as the default case.

**Comment by thewatts** [comment]
@rossta Most welcome! Really excited about this project.

Apologies that I didn't specify specific increment requirements for `except` - had been looking for the feature this morning, and saw the `README` had a `todo` with an example api, I figured you were wanting it to be as such.

Definitely agree tho! Perhaps passing in a Hash of specifications?

```ruby
recurrence.except({ dates: ["2016-03-01"], days: [:sunday], months: [:february] })
```

**Comment by rossta** [comment]
Just to clarify, what you submitted is the right way to start. My previous comment and the ones that follow are more like "thinking out loud". 

I haven't decided whether it `:except` should be more than just exclusion by date. We could add something like what you described; the extreme version of this would be to support all/most the same options for recurrence as a nested hash to `:except`. 

At that stage, `Montrose::Recurrence` could behave like a set. The `:except` option would represent set exclusion, i.e. [`Set#^`](http://ruby-doc.org/stdlib-2.3.0/libdoc/set/rdoc/Set.html#method-i-5E), whereas `Recurrence#merge` is already a corollary of set addition. Along those lines, there may be a place for recurrence "intersection" and "union" to take the analogy further. That approach is more aligned with Martin Fowler's discussion of [temporal expressions for recurring events](http://martinfowler.com/apsupp/recurring.pdf). That would all mean implementing the set operators `#+`, `#&`, `#^`, etc. in terms of `Recurrence`. Again, not sure if this is right for Montrose, but interesting to consider.

**Comment by vakrolme** [comment]
@rossta, iCalendar has exrule standard, and ice_cube [has](https://github.com/seejohnrun/ice_cube/blob/d0a6b6a50176048cd33e058f0151b63e543d016a/lib/ice_cube/schedule.rb) `IceCube::Schedule.add_exception_rule`. Since Montrose now has schedules as well, how difficult is it going to be to implement exrules there?

**Pull request merged**
